# Generated by Django 3.2.3 on 2021-06-09 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesejWhatsapp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_sid', models.CharField(default='NA', max_length=255)),
                ('account_sid', models.CharField(default='NA', max_length=255)),
                ('profile_name', models.CharField(default='NA', max_length=255)),
                ('body', models.CharField(default='NA', max_length=255)),
                ('whatsapp_id', models.CharField(default='NA', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
