# Generated by Django 3.2.3 on 2021-06-13 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0002_bantuan_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_id', models.CharField(default='NA', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatroomMesej',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(default='NA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='whatsapp_id',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='mesejwhatsapp',
            name='body',
            field=models.TextField(default='NA'),
        ),
    ]
