# Generated by Django 3.2.3 on 2021-06-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0003_auto_20210613_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommesej',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpdnhep_eaduan.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroommesej',
            name='pengguna',
            field=models.BooleanField(default=True),
        ),
    ]
