# Generated by Django 3.2.3 on 2021-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0004_auto_20210613_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduan',
            name='body',
            field=models.TextField(default='NA'),
        ),
    ]
