# Generated by Django 3.2.3 on 2021-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0006_auto_20210613_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduan',
            name='tugas',
            field=models.BooleanField(default=False),
        ),
    ]
