# Generated by Django 3.2.3 on 2021-06-15 00:00

from django.db import migrations, models
import helpers.general


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0008_auto_20210614_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantuan',
            name='topik_bantuan',
            field=models.CharField(choices=[('A', 'Gangguan Sistem'), ('B', 'Pertanyaan')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='bantuan',
            name='dokumen',
            field=models.FileField(null=True, upload_to=helpers.general.PathAndRename('kpdnhep')),
        ),
    ]
