# Generated by Django 3.2.3 on 2021-06-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpdnhep_eaduan', '0009_auto_20210615_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantuan',
            name='mesej',
            field=models.TextField(default='NA'),
        ),
    ]
