# Generated by Django 3.2.3 on 2021-06-03 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceiveReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PO_Number', models.CharField(default='NA', max_length=255)),
                ('Change_Order_Number', models.CharField(default='NA', max_length=255)),
                ('Change_Order_Status', models.CharField(default='NA', max_length=255)),
                ('Description', models.CharField(default='NA', max_length=255)),
                ('Procurement_BU', models.CharField(default='NA', max_length=255)),
                ('SoldTo_Legal_Entity', models.CharField(default='NA', max_length=255)),
                ('Buyer', models.CharField(default='NA', max_length=255)),
                ('Supplier_Number', models.CharField(default='NA', max_length=255)),
                ('Supplier_Name', models.CharField(default='NA', max_length=255)),
                ('Supplier_Site_Code', models.CharField(default='NA', max_length=255)),
                ('Address_Name', models.CharField(default='NA', max_length=255)),
                ('Address_Line1', models.CharField(default='NA', max_length=255)),
                ('Address_Line2', models.CharField(default='NA', max_length=255)),
                ('Address_Line3', models.CharField(default='NA', max_length=255)),
                ('City', models.CharField(default='NA', max_length=255)),
                ('State', models.CharField(default='NA', max_length=255)),
                ('Postal_Code', models.CharField(default='NA', max_length=255)),
                ('Country', models.CharField(default='NA', max_length=255)),
                ('Contact_First_Name', models.CharField(default='NA', max_length=255)),
                ('Contact_Last_Name', models.CharField(default='NA', max_length=255)),
                ('Contact_Email_Address', models.CharField(default='NA', max_length=255)),
                ('Contact_Mobile_Number', models.CharField(default='NA', max_length=255)),
                ('Contact_Phone_Number', models.CharField(default='NA', max_length=255)),
                ('Supplier_Contact', models.CharField(default='NA', max_length=255)),
                ('Line_Num', models.CharField(default='NA', max_length=255)),
                ('Schedule_Num', models.CharField(default='NA', max_length=255)),
                ('Distribution_Num', models.CharField(default='NA', max_length=255)),
                ('Item_Number', models.CharField(default='NA', max_length=255)),
                ('Line_Description', models.CharField(default='NA', max_length=255)),
                ('Quantity', models.CharField(default='NA', max_length=255)),
                ('UOM_Code', models.CharField(default='NA', max_length=255)),
                ('Base_Quantity', models.CharField(default='NA', max_length=255)),
                ('Base_UOM_Code', models.CharField(default='NA', max_length=255)),
                ('Requested_Date', models.CharField(default='NA', max_length=255)),
                ('Ship_to_Organization', models.CharField(default='NA', max_length=255)),
                ('Ship_to_Organization_Name', models.CharField(default='NA', max_length=255)),
                ('SubInventory_Code', models.CharField(default='NA', max_length=255)),
                ('Ship_to_Location', models.CharField(default='NA', max_length=255)),
                ('Line_Type', models.CharField(default='NA', max_length=255)),
                ('Line_Status', models.CharField(default='NA', max_length=255)),
                ('Requester', models.CharField(default='NA', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
