# Generated by Django 3.2.3 on 2021-06-18 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airsel_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrTransactionChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Item_Number', models.CharField(default='', max_length=255)),
                ('Description', models.CharField(default='', max_length=255)),
                ('Long_Description', models.CharField(default='', max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MrTransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airsel_inventory.mrtransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
