# Generated by Django 3.2.3 on 2021-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsel_inventory', '0003_grninterface2interface_grninterfaceinterface_inventorytransactionfrommaintenanceinterface_inventoryt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrnInterface2Interface',
        ),
        migrations.DeleteModel(
            name='InventoryTransactionFromMaintenanceInterface',
        ),
        migrations.DeleteModel(
            name='InventoryTransactionFromProjectInterface',
        ),
        migrations.DeleteModel(
            name='ItemInterface',
        ),
        migrations.DeleteModel(
            name='MaterialRequestInterface',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderInterface',
        ),
        migrations.AddField(
            model_name='grninterfaceinterface',
            name='Reason',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='grninterfaceinterface',
            name='Remarks',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
