# Generated by Django 3.2.3 on 2021-06-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0002_elaun_elaunperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elaun',
            old_name='tarikh',
            new_name='tarikh_akhir',
        ),
        migrations.AddField(
            model_name='elaun',
            name='tarikh_mula',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaunperson',
            name='pemohon',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='hari',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='kadar_jam',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='tujuan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='waktu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
