# Generated by Django 3.2.3 on 2021-06-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0003_auto_20210605_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaun',
            name='pegawai_lulus_catatan',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaun',
            name='pegawai_luluskan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elaun',
            name='pegawai_sah_catatan',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaun',
            name='pegawai_sahkan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elaun',
            name='status',
            field=models.CharField(choices=[('01', 'Dalam Permohonan'), ('02', 'Menunggu Pengesahan oleh Pegawai Pengesah'), ('03', 'Pengesahan Ditolak'), ('04', 'Menunggu Kelulusan oleh Pegawai Pelulus'), ('05', 'Kelulusan Ditolak'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
