# Generated by Django 3.2.3 on 2021-06-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0004_auto_20210606_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaun',
            name='hari',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='kadar_jam',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='masa_akhir',
            field=models.TimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='masa_mula',
            field=models.TimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='pegawai_lulus_catatan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='pegawai_sah_catatan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='tarikh_akhir',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='tarikh_mula',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='waktu',
            field=models.FloatField(null=True),
        ),
    ]
