# Generated by Django 3.2.3 on 2021-06-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0005_auto_20210606_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaun',
            name='masa_akhir',
        ),
        migrations.RemoveField(
            model_name='elaun',
            name='masa_mula',
        ),
        migrations.AlterField(
            model_name='elaun',
            name='status',
            field=models.CharField(choices=[('00', 'Dalam Permohonan'), ('01', 'Menunggu Pengesahan oleh Pegawai Pengesah'), ('02', 'Pengesahan Ditolak'), ('03', 'Menunggu Kelulusan oleh Pegawai Pelulus'), ('04', 'Kelulusan Ditolak'), ('05', 'Menunggu Kelulusan oleh Datuk Bandar'), ('06', 'Boleh dituntut'), ('07', 'Dalam tuntutan'), ('08', 'Semakan oleh Perbendaharaan'), ('09', 'Pindaan oleh Perbendaharaan'), ('10', 'Lulus - Dimasukkan Dalam Gaji'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='tarikh_akhir',
            field=models.DateTimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elaun',
            name='tarikh_mula',
            field=models.DateTimeField(max_length=255),
        ),
    ]
