# Generated by Django 3.2.3 on 2021-06-06 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0006_auto_20210606_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaun',
            name='masa',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
