# Generated by Django 3.2.3 on 2021-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0008_alter_elaun_masa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaun',
            name='masa',
            field=models.DurationField(null=True),
        ),
    ]
