# Generated by Django 3.2.3 on 2021-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0009_alter_elaun_masa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaunperson',
            name='kod_pekerja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elaunperson',
            name='nric',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
