# Generated by Django 3.2.3 on 2021-06-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbpj_elaun', '0011_elauntuntutan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elauntuntutan',
            name='elaun',
        ),
        migrations.AddField(
            model_name='elauntuntutan',
            name='elaun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mbpj_elaun.elaun'),
        ),
    ]
