# Generated by Django 3.1.5 on 2021-05-15 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('NA', 'Not Available'), ('NA', 'Not Available'), ('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
    ]
