# Generated by Django 3.2.3 on 2021-06-17 12:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='location',
        ),
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='checkin',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
