# Generated by Django 3.2.3 on 2021-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piper', '0002_auto_20210617_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='location',
            field=models.CharField(choices=[('HQ', 'HQ Office'), ('CY', 'Cyberjaya Office'), ('CL', 'Client Office'), ('HO', 'Home'), ('NA', '')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='checkin',
            name='purpose',
            field=models.CharField(choices=[('AW', 'Start Work'), ('EW', 'End Work'), ('AS', 'Start Site Meeting or Work'), ('ES', 'End Site Meeting or Work'), ('AO', 'Start Overtime'), ('EO', 'End Overtime'), ('NA', '')], default='NA', max_length=2),
        ),
    ]
