# Generated by Django 3.1.5 on 2021-05-15 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True, unique=True)),
                ('address_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('verification_dt', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-creation_dt'],
            },
        ),
    ]
