# Generated by Django 3.2.3 on 2021-05-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210515_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address_type',
            field=models.CharField(choices=[('S8', 'SS58 & Substrate Wallet'), ('ET', 'Ethereum Wallet'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
